version: "3.8"
services:
  web:
    build:
      context: ./dockerfiles/nginx
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-shojib}
    container_name: nginx-container
    ports:
      - "9090:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./dockerfiles/nginx/log:/var/log/nginx
#      move to nginx.dockerfile
#      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /var/www/html
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
